container:
  image: ubuntu:latest

build_task:
  require_script:
  - apt-get update
  - apt-get install -y build-essential bison flex rake git curl
  mruby_cache:
    folder: mruby
    fingerprint_script: git -C mruby rev-parse HEAD
    populate_script: git submodule update --init --recursive
  build_script: rake
