container:
  image: buildpack-deps:bionic-scm

task:
  env:
    MIRROR: http://gce.clouds.archive.ubuntu.com/ubuntu
  apt_script:
  - . /etc/lsb-release
  - echo '# Ubuntu GCE Mirror Repository'                                                  >  /etc/apt/sources.list
  - echo "deb ${MIRROR} ${DISTRIB_CODENAME}           main restricted universe multiverse" >> /etc/apt/sources.list
  - echo "deb ${MIRROR} ${DISTRIB_CODENAME}-updates   main restricted universe multiverse" >> /etc/apt/sources.list
  - echo "deb ${MIRROR} ${DISTRIB_CODENAME}-backports main restricted universe multiverse" >> /etc/apt/sources.list
  - echo "deb ${MIRROR} ${DISTRIB_CODENAME}-security  main restricted universe multiverse" >> /etc/apt/sources.list
  - apt-get -y update
  - apt-get -y dist-upgrade
  - apt-get -y install make gcc bison flex rake git curl ca-certificates
  mruby_cache:
    folder: mruby
    fingerprint_script: git submodule status
    populate_script: git submodule update --init --recursive
  build_script: rake
  binaries_artifacts:
    path: "bin/cmitamae"
