container:
  image: ubuntu:latest

build_task:
  setup_script:
  - apt-get update
  - apt-get install -y build-essential bison flex rake git
  - git submodule update --init --recursive
  build_script: rake
