dist: xenial
language: c
compiler:
- gcc
addons:
  apt:
    packages:
    - make
    - gcc
    - bison
    - flex
    - rake
    - git
    - curl
    - ca-certificates
script:
- rake
deploy:
  provider: releases
  api_key:
    secure: It7dy7kcdBrLbgByESDMLSZLGY9bHC56978WlHga+kcO5lPjGRRiv6245DMgTABAZ1CPbWJG7U4t+JSPH1Sc+otPQhubyXjvT/gI9jso8mriSMhwIJI0eiyxmthgCHbjzrd3a2GduZU+Q0aoH+8Uazz/ZglslbjqhfWC1YskCM/mo7QX8/PPMoFu6GxK801Tl0DVdQAU+VDJY/ESonjo9XINaknUeLKmNiXiK8neKBL4AnyLf4d/1Hzi0F3AwxM7tJHEPTjP2q8Y+/i8myAlWoTNXy83VOtdRI3Mt/bbK0a6y+ny7z2g192dMszPIBthHkFNr1ygwZ1gQXIWPqBNQaK8IMNr0dV7JjTMolvmAPay1c1/j5mbUKkpN51X//TEL01z+PqKbkGiskeCnRKL5t4rYx2CweR9pr4tZCASQXNanpkC6E41flQH3kQ+9OSMtSJVrIeCQSFSXrVbXCNbaLUVbFy05LjmO/sQDKBz8cmra8FUOn0A/JF9Z/v6uZY+TtqbVenUv8A0kb7Dkcrl+jZrM6nIHm4t4vFWEAK5SIVpS/b749UWotIM8INMahE76/GrZWN9zXToJ5m0Hu9FLJJQMx2iYo7l0XejeEwhTQUS8RbnyUw86XWubBU6+LZz+4pJB+IRNi204gQvBSkfdiuFPAbFGBYBNxpyWDosffc=
  file:
  - bin/cmitamae
  on:
    repo: takumin/cmitamae
    tags: true
    all_branches: true
  skip_cleanup: true
