name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
        fetch-depth: 1
    - name: Dependency
      run: |-
        sudo apt-get -y update
        sudo apt-get -y --no-install-recommends install make gcc g++ bison flex rake curl ca-certificates
    - name: Build
      run: rake
